# Generated by Django 4.2.6 on 2023-10-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CHAIRMAN_OF_DEPARTMENT', 'Chairman of Department'), ('LIBRARY', 'Library'), ('SPORTS_AND_ENTERTAINMENT', 'Sports and entertainment'), ('HOSTELS', 'Hostels'), ('FINANCE', 'Finance'), ('DEAN_OF_STUDENTS', 'Dean of Students'), ('REGISTRAR', 'Registrar'), ('STUDENT', 'Student')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=8),
        ),
    ]
