# Generated by Django 4.2.6 on 2023-12-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CHAIRMAN_OF_DEPARTMENT', 'Chairman of Department'), ('LIBRARY', 'Library'), ('SPORTS_AND_ENTERTAINMENT', 'Sports and entertainment'), ('HOSTELS', 'Hostels'), ('FINANCE', 'Finance'), ('DEAN_OF_STUDENTS', 'Dean of Students'), ('REGISTRAR', 'Registrar'), ('STUDENT', 'Student')], max_length=30),
        ),
    ]
