# Generated by Django 4.2.6 on 2023-10-28 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('clearance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
