# Generated by Django 4.2.6 on 2023-11-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='approved',
            field=models.CharField(max_length=10),
        ),
    ]
