# Generated by Django 4.2.6 on 2023-10-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0002_alter_clearance_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
